### ISSUE TITLE
Version isn't displayed on production.

### ISSUE THREAD

**Issue by fivitti** [gut-space/satnogs#67] opened 2020-04-11 19:02 UTC
Version and timestamp isn't present on production server.
We need fix it and add unittest for check if it works.

**Comment by tomaszmrugalski** [comment] 2020-04-11 21:53
> We need fix it 

Yes. Fixed in 960f042d1474bb1039c2c5b0e1807aec27bb5f98

> and add unittest for check if it works.

No. The problem was caused by the timestamp being checked on the file itself (without full path). This only happened if you ran the server from a different directory than the sources. This is a marginal deployment nuance. IMHO writing unit-tests for this would be both tricky and a waste of time.

**Closed as completed by tomaszmrugalski** 2020-04-11 21:53 UTC
Labels: bug, server, ui
